# The default build. It really makes no difference which target is the default
# and which are defined though the build matrix.
language: c
compiler: gcc
script: mkmk init --config tclib.mkmk && ./build.sh run-tests
install: source ./tools/enter-devenv.sh
