# The default build. It really makes no difference which target is the default
# and which are defined though the build matrix.
language: c
compiler: gcc
script: python ci.py run --debug --noisy -- all run-tests
install: ./tools/ci.py begin --config tclib.mkmk
sudo: false

matrix:
  include:
    # Test a clang build in debug mode under valgrind.
    - language: c
      compiler: clang
      script: python ci.py run --debug --valgrind --noisy -- all run-tests
      install: ./tools/ci.py begin --config tclib.mkmk
      addons:
        apt:
          packages:
          - valgrind
    # Test everything using an optimized clang build.
    - language: c
      compiler: clang
      script: python ci.py run --noisy -- all run-tests
      install: ./tools/ci.py begin --config tclib.mkmk
    # Test with checks disabled.
    - languate: c
      compiler: clang
      script: python ci.py run --nochecks --noisy -- all run-tests
      install: ./tools/ci.py begin --config tclib.mkmk
    # Check that the C code compiles using gcc.
    - language: c
      compiler: gcc
      script: python ci.py run --debug --noisy -- all run-tests
      install: ./tools/ci.py begin --config tclib.mkmk
